# Generated by Django 5.2 on 2025-04-26 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstitucionFinanciera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='instituciones/')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('BANCO', 'Banco'), ('COOPERATIVA', 'Cooperativa')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoInversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100)),
                ('plazo_dias', models.PositiveIntegerField()),
                ('tea', models.DecimalField(decimal_places=2, max_digits=5)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inversiones.institucionfinanciera')),
            ],
        ),
    ]
