# Generated by Django 5.2 on 2025-04-26 18:07

import apps.inversiones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inversiones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoinversion',
            name='tea',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[apps.inversiones.models.validacion]),
        ),
    ]
